package com.mm.Const

const val CONFIG_ACTIVATE_MESSAGE_TEMPLATE = "activate.message.template"
const val CONFIG_ACTIVATE_URL_TEMPLATE = "activate.url.template"
const val CONFIG_SECRET_DATABASE = "secret.database.config"
const val CONFIG_MIAL_SERVICE = "mail.service.config"
const val CONFIG_HTTP_PORT = "http.port"

const val SESSION_KEY_USERINFO = "user_info"
const val SESSION_KEY_TOKEN = "mtoken"
const val REQ_PARAM_KEY_EMAIL = "email"
const val REQ_PARAM_KEY_PASSWORD = "password"
const val HEADER_KEY_MTOKEN = "mtoken"
const val REQ_PARAM_KEY_SEX = "sex"
const val REQ_PARAM_KEY_UUID = "uuid"
const val REQ_PARAM_KEY_AVTIVATE_CODE = "activate_code"
const val REQ_PARAM_KEY_USERPASS_ID = "upassId"
const val REQ_PARAM_KEY_USERPASS_DATA = "data"
const val REQ_PARAM_KEY_USERPASS_WEIGHT = "weight"
const val REQ_PARAM_KEY_USERPASS_SWAP_TO = "toUid"
const val REQ_PARAM_WEIGHT_TOP = "top"
const val REQ_PARAM_WEIGHT_SWAP = "swap"